# Generated by Django 6.1 on 2026-08-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='math',
            old_name='math',
            new_name='math1',
        ),
        migrations.AddField(
            model_name='math',
            name='math2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
