# Generated by Django 6.1 on 2026-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_math_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
